- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Create containerd config file
  shell: containerd config default > /etc/containerd/config.toml

- name: Setting crictl endpoint
  shell: crictl config --set runtime-endpoint=unix:///run/containerd/containerd.sock --set image-endpoint=unix:///run/containerd/containerd.sock

- name: Enable systemd cgroup
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    insertafter: "{{item.insertafter}}"
  with_items:
    - regexp: "            SystemdCgroup = false"
      line: "            SystemdCgroup = true"
      insertafter: 'plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options'
  notify:
    - Restart containerd
